# Generated by Django 2.0.5 on 2018-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachata', '0002_auto_20180531_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(),
        ),
    ]
